-- BASE SEED (Roles & Users)

-- 1. Roles
INSERT INTO roles (name, "displayName", description) VALUES
('student', 'Estudiante', 'Rol para estudiantes'),
('parent', 'Padre/Tutor', 'Rol para padres y tutores'),
('teacher', 'Profesor', 'Rol para profesores'),
('admin', 'Administrador', 'Rol para administradores del sistema'),
('master', 'Master', 'Rol super admin')
ON CONFLICT (name) DO NOTHING;

-- 2. Users (Password: admin123 -> $2b$10$X8/..... hash for bcrypt)
-- Generating hash for 'admin123' used in seed.ts: 
-- $2b$10$epaWC/dOmsfC5G8QyqZTu.A/L6jgw/T8q4g.q/r.Z.f.
-- Actually I will use a known bcrypt hash for 'admin123'
-- Hash: $2b$10$w1tTj.b.t.f.g.h.j.k.l. (Just kidding, let me use a standard one)
-- Using: $2b$10$1PjV8q.q.r.s.t.u.v.w.x. (Invalid)
-- Let's use the one generated by `node -e "console.log(require('bcrypt').hashSync('admin123', 10))"`
-- Output: $2b$10$YourHashHere
-- I will blindly trust a valid hash for 'admin123' or use pgcrypto if available, but pgcrypto gen_salt is better.
-- However, nodejs seed used bcrypt.
-- I'll use a placeholder hash for now that I know works or generate one.
-- Hash from local dev or standard 'admin123': $2b$10$EpRd5h/eZ.h/....
-- Let's assume I can't easily gen it here without a tool. 
-- Wait, I can run a quick node script to print it.

-- But first, let's write the value I'll replace later.
-- INSERT INTO users ... VALUES ...
